Now Evaluating
Evaluating for 100 steps
/home/da2986/anaconda3/lib/python3.9/site-packages/transformers/generation_utils.py:1359: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 512 (`self.config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Traceback (most recent call last):
  File "/home/da2986/Summarization/src/training_scripts/cnn_bert/generate_and_evaluate.py", line 214, in <module>
    evaluator.evaluate()
  File "/home/da2986/Summarization/src/training_scripts/evaluator.py", line 50, in evaluate
    loss = self.validation_step(val_data, self.model, self.val_metrics, val_steps, log = False, wandb = self.wandb, args = self.args, file_name = self.file_name)
  File "/home/da2986/Summarization/src/training_scripts/cnn_bert/generate_and_evaluate.py", line 116, in validation_step
    file.write('All article text:' + data['all_text'][i] + '\n')
KeyError: 'all_text'
0